### ISSUE TITLE
spacemacs下无法启动

### ISSUE THREAD

**Issue by jinboowu** [Kinneyzhang/gk-roam.el#23]
任何命令都会返回   Cannot open load file: No such file or directory, db 

win10 下的spacemacs

**Comment by Kinneyzhang** [comment]
这个是因为没有安装依赖: db。如果你是从melpa安装的，按理说会自动安装这个依赖。问题不大，你可以手动装一下，package名称就叫: db。

**Comment by jinboowu** [comment]
感谢 问题已解决  gkroam是手动下载的包

**Comment by Kinneyzhang** [comment]
Ok, 欢迎反馈问题和需求。
