### ISSUE TITLE
WIN10 下spacemacs 无法显示linked reference

### ISSUE THREAD

**Issue by jinboowu** [Kinneyzhang/gk-roam.el#24]
在windows以及wsl的ubuntu系统里都安装了gkroam

wsl里面可以看到linked reference 而在win下面就没有显示linked refence也没有错误提示

exec-find 可以找到ripgrep（用scoop安装） 不知道怎么解决这个问题

**Comment by Kinneyzhang** [comment]
修复了 issue #30 , 或许是这个原因？你可以安装最新的版本再试试。

**Comment by jinboowu** [comment]
win下的 spacemacs该问题已解决但碰到了和这个一样的类似问题 https://github.com/Kinneyzhang/gkroam/issues/25
