### ISSUE TITLE
gkroam-link-with-headline-re may match incorrectly

### ISSUE THREAD

**Issue by Whil-** [Kinneyzhang/gk-roam.el#33]
With the following example text:

```
A {[Link1]} and another {[Link2 » With Heading]} exist on the same line
```
`gkroam-link-with-headline-re` doesn't know better than to match the first part with `Link1]} and another {[Link2` while the correct match should be `Link2`

**Comment by Kinneyzhang** [comment]
Thanks for figuring out the bug. But I prefer this change: 
```
(defvar gkroam-link-with-headline-re "{\\[\\(.+?\\) » \\(.+?\\)\\].*?}")
```
instead of doing 'traceback' in consideration of efficiency.

**Comment by Whil-** [comment]
Hi @Kinneyzhang, while I agree that performance should be considered the fix you suggest doesn't actually fix the problem.

When the regexp parser is looking at the third character on the example line above (repeated here):
```
A {[Link1]} and another {[Link2 » With Heading]} exist on the same line
```
it will still match all the way to the ending brackets after the second link. Since the regexp doesn't know how to stop the match when encountering the end-brackets at the first link.

So unfortunately this is still a bug and the pull-request I sent will still fix it.

Looking through the source code it seems `gkroam-search-all-headline-links` suffers from the same issue. Although in that case it likely doesn't matter...

**Comment by Kinneyzhang** [comment]
It seems that you have misunderstood the function of ```gkroam-cache-curr-headline-links```. The purpose of the function is to put headline and headline id in caches, so it only need to match headline links.

As to the example:
```
A {[Link1]} and another {[Link2 » With Heading]} exist on the same line
```
the first link is a page link and the second one is a headline link.

**Comment by Whil-** [comment]
I might have misunderstood, although I'm not so sure that's the case. What I'm pointing at is that the function never gets to parse the second link correctly, since it manages to find a match that spans both links (which is wrong) and thus will never parse the second link.

Please try to run the regexp search on the example line I added and see what happens. If you mean that it is okay for the function to end up with the first group in the regexp  matched with `Link1]} and another {[Link2`, then I indeed misunderstood something.

**Comment by Kinneyzhang** [comment]
I have run the regexp ```"{\\[\\(.+?\\) » \\(.+?\\)\\].*?}"``` search on the example line and the point gone to the end of ```{[Link2 » With Heading]}```. It means the regexp have match the second headline link. Then, the function ```gkroam-set-headline-id``` set the headline's (first match string) id for page titled with title (first match string) and cache them in db.

```emacs-lisp
(defun gkroam-cache-curr-headline-links ()
  "Cache current page's gkroam headline links."
  (save-excursion
    (goto-char (point-min))
    (while (re-search-forward gkroam-link-with-headline-re nil t)
      (gkroam-set-headline-id
       (match-string-no-properties 1)
       (match-string-no-properties 2)))))
```

**Comment by Whil-** [comment]
And what is the content of the `(match-string-no-properties 1)` on your end? For me it's not only `Link2`.

**Comment by Kinneyzhang** [comment]
Sorry, I see the problem. 😅
