### ISSUE TITLE
Deleting a daily note doesn't work correctly due to comma in the title

### ISSUE THREAD

**Issue by stephenhay** [Kinneyzhang/gk-roam.el#40]
When trying to delete a daily note, it's possible to delete multiple notes by separating their titles with a comma. However—possibly depending on the user's default date format—the title of the daily note itself contains a comma. This results in the delete function thinking it has to delete two files (example: "Nov 11" and "2020". Delete doesn't work because it can't find those files because (luckily in this case) they don't exist.

This of course results in deleting via e.g. dired, which requires looking up the unique filename ID.

![image](https://user-images.githubusercontent.com/473099/98981137-de5f5100-251d-11eb-9441-c6d3909ba077.png)

**Comment by Kinneyzhang** [comment]
What's the version of gkroam you have installed? Please use the latest version.

https://github.com/Kinneyzhang/gkroam/blob/831efb213e5af0fc55067d9c06df8c775491c8e5/gkroam.el#L1567-L1571

**Comment by stephenhay** [comment]
I installed the latest version it now works fine, @Kinneyzhang, thanks!
