### ISSUE TITLE
gkroam-update causes error in process sentinel in gkroam 2.4.2

### ISSUE THREAD

**Issue by sjmarshy** [Kinneyzhang/gk-roam.el#43]
I'm getting the following error when running `M-x gkroam-update` in any file. I've ran `gkroam-rebuild-caches`, but I'm still getting the error afterwards.

```
error in process sentinel: gkroam--format-linked-reference-content: Args out of range: #<killed buffer>, 442, 659
error in process sentinel: Args out of range: #<killed buffer>, 442, 659
```

Thanks for your help.

**Comment by Kinneyzhang** [comment]
I cannot reproduce the error. Did you use the stable version 2.4.2 ? If so, please try to use the latest commit.

**Comment by sjmarshy** [comment]
I was using the latest commit. It's difficult to figure out when the error is happening - it doesn't happen on every single page, but I have a few thousand files which I'm migrating from org style links through to gkroam. Which makes finding what common factors exist between the files where this error happens quite difficult. I'll continue to try and find a minimal reproduction of the error.

**Comment by Whil-** [comment]
(Sidetrack @sjmarshy: if you're migrating a whole library you might find the following functions helpful: https://gist.github.com/Whil-/b7e4a5dd58c245fe1a3e0164107e3297

In the bottom are the functions that will go through your library. Don't use unless you have your files under version control though.)
