### ISSUE TITLE
我想问一下，orgmode里面的三键快捷键怎么按呀？

### ISSUE THREAD

**Issue by Rao-Jupiter** [Kinneyzhang/gk-roam.el#52]
请问一下，像 C-c r I 这种快捷键怎么按呀？为什么我只能按 C-c r 就结束了？

**Comment by Kinneyzhang** [comment]
看一下你的 `C-c r` 是不是已经定义了快捷命令。是的话，需要取消这个前缀的绑定，或者给gkroam换个前缀绑定。

**Comment by Rao-Jupiter** [comment]
没有，emacs就是提示 undefine🤣

**Comment by Kinneyzhang** [comment]
readme里面的配置加到你的配置里面执行力没？没有绑定快捷键，自然就是undefine。
