### ISSUE TITLE
Reason for custom link notation?

### ISSUE THREAD

**Issue by clemera** [Kinneyzhang/gk-roam.el#7]
I haven't tried gk-roam after your initial announcement but I'm interested how it evolves. I'm a bit concerned about the use of a special link syntax, what were the reasons to introduce it?

**Comment by Kinneyzhang** [comment]
As you know, roam research uses "[[]]" and "#[[]]" to represent page link and hashtag link. I just imitated roam research in the aspect of 'brackets link' and hashtag. But, org-mode treats "[[]]" as org link, so I changed it to "{[]}", the same is for hashtag. 

Another reason is related to link search. As gk-roam uses 'rg' to search links in all pages and then insert references respectively at the bottom of every page, if it used org link as page link or hashtag, 'rg' would confuse page links with backlinks in references. The result is rg will treat backlinks as a valid page link and insert a reference referred to current page.  That does not make sense! 

So, use differnent notation for page links and backlinks may be a good idea.

**Comment by clemera** [comment]
Sorry I'm not that familiar with concepts of org and roam in general I just assumed you insert file links and and see which files link to the current one. What are page links and hashtag links are used for?

**Comment by Kinneyzhang** [comment]
> What are page links and hashtag links are used for? 

Maybe you could watch these [videos](https://www.youtube.com/playlist?list=PLwXSqDdn_CpE934BjXMgmzHnlwXMy41TC) to know more about roam. After that, you will know how powerful bracket link and hashtag are. Gk-roam almostly imitates roam research in many aspects and if you think roam is useful to you, definitely you shoud have a try of gk-roam in emacs. Haha, have fun!

**Comment by clemera** [comment]
Thanks for the link! Org-mode links are quite customizable maybe one could add those features as additional link types and distinguish them via rg, too?

> Simply speaking, page link is a reference to another page, the same as hashtag. But hashtag is usually treated as a tag semantically.

What are pages in this context? Are they headline bodies?

**Comment by Kinneyzhang** [comment]
"pages" here means org files.

**Comment by clemera** [comment]
Okay, thanks for working on this, seems like a useful lightweight addition to the roam related packages out there!
